flask练习/movie_project/app/home/forms.py
# coding:utf8
"""
Created by dreamkong on 2018/10/31
"""
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, FileField, TextAreaField

from wtforms.validators import DataRequired, EqualTo, Email, Regexp, ValidationError

from app.models import User

__author__ = 'dreamkong'


class RegisterForm(FlaskForm):
    name = StringField(
        label='昵称',
        validators=[
            DataRequired('请输入昵称！')
        ],
        description='昵称',
        render_kw={
            'class': 'form-control input-lg',
            'placeholder': '请输入昵称！',
            'required': False
        }
    )
    email = StringField(
        label='邮箱',
        validators=[
            DataRequired('请输入邮箱！'),
            Email('邮箱格式不正确！')
        ],
        description='邮箱',
        render_kw={
            'class': 'form-control input-lg',
            'placeholder': '请输入邮箱！',
            'required': False
        }
    )
    phone = StringField(
        label='手机号码',
        validators=[
            DataRequired('请输入手机号码！'),
            Regexp('1[345789]\d{9}', message='手机号码格式不正确！')
        ],
        description='手机号码',
        render_kw={
            'class': 'form-control input-lg',
            'placeholder': '请输入手机号码！',
            'required': False
        }
    )
    password = PasswordField(
        label='密码',
        validators=[
            DataRequired('请输入密码！')
        ],
        description='密码',
        render_kw={
            'class': 'form-control input-lg',
            'placeholder': '请输入密码！',
            'required': False
        }
    )
    repassword = PasswordField(
        label='确认密码',
        validators=[
            DataRequired('请确认密码！'),
            EqualTo('password', '两次密码不一致')
        ],
        description='确认密码',
        render_kw={
            'class': 'form-control input-lg',
            'placeholder': '请确认密码！',
            'required': False
        }
    )
    submit = SubmitField(
        label='注册',
        render_kw={
            'class': 'btn btn-lg btn-success btn-block'
        }
    )

    def validate_name(self, field):
        name = field.data
        user = User.query.filter_by(name=name).count()
        if user == 1:
            raise ValidationError('昵称已经存在！')

    def validate_email(self, field):
        email = field.data
        user = User.query.filter_by(email=email).count()
        if user == 1:
            raise ValidationError('邮箱已经存在！')

    def validate_phone(self, field):
        phone = field.data
        user = User.query.filter_by(phone=phone).count()
        if user == 1:
            raise ValidationError('电话号码已经存在！')


class LoginForm(FlaskForm):
    name = StringField(
        label='账号',
        validators=[
            DataRequired('请输入账号！')
        ],
        description='账号',
        render_kw={
            'class': 'form-control input-lg',
            'placeholder': '请输入账号！',
            'required': False
        }
    )
    password = PasswordField(
        label='密码',
        validators=[
            DataRequired('请输入密码！')
        ],
        description='密码',
        render_kw={
            'class': 'form-control input-lg',
            'placeholder': '请输入密码！',
            'required': False
        }
    )
    submit = SubmitField(
        label='登录',
        render_kw={
            'class': 'btn btn-lg btn-success btn-block'
        }
    )


class UserDetailForm(FlaskForm):
    name = StringField(
        label='昵称',
        validators=[
            DataRequired('请输入昵称！')
        ],
        description='昵称',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入昵称！',
            'required': False
        }
    )
    email = StringField(
        label='邮箱',
        validators=[
            DataRequired('请输入邮箱！'),
            Email('邮箱格式不正确！')
        ],
        description='邮箱',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入邮箱！',
            'required': False
        }
    )
    phone = StringField(
        label='手机号码',
        validators=[
            DataRequired('请输入手机号码！'),
            Regexp('1[345789]\d{9}', message='手机号码格式不正确！')
        ],
        description='手机号码',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入手机号码！',
            'required': False
        }
    )
    avatar = FileField(
        label='头像',
        validators=[
            DataRequired('请上传头像！')
        ],
        description='头像',
        render_kw={
            'required': False
        }
    )
    info = TextAreaField(
        label='简介',
        validators=[
            DataRequired('请输入简介！'),
        ],
        description='简介',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入简介！',
            'rows': '10',
            'required': False
        }
    )
    submit = SubmitField(
        label='保存修改',
        render_kw={
            'class': 'btn btn-success'
        }
    )


class PasswordForm(FlaskForm):
    old_password = PasswordField(
        label='旧密码',
        validators=[
            DataRequired('请输入旧密码！')
        ],
        description='旧密码',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入旧密码！',
            'required': False
        }
    )
    new_password = PasswordField(
        label='新密码',
        validators=[
            DataRequired('请输入新密码！')
        ],
        description='新密码',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入新密码！',
            'required': False
        }
    )
    submit = SubmitField(
        label='确定',
        render_kw={
            'class': 'btn btn-primary'
        }
    )

    def validate_old_password(self, field):
        from flask import session
        old_password = field.data
        name = session['user']
        user = User.query.filter_by(name=name).first()
        print('kakkaakakak')
        if not user.check_password(old_password):
            raise ValidationError('旧密码不正确！')


class CommentForm(FlaskForm):
    content = TextAreaField(
        label='评论内容',
        validators=[
            DataRequired('请输入评论内容！'),
        ],
        description='评论内容',
        render_kw={
            'id':'input_content',
            'required': False
        }
    )
    submit = SubmitField(
        label='提交评论',
        render_kw={
            'class': 'btn btn-success'
        }
    )

flask练习/movie_project/app/home/__init__.py
"""
Created by dreamkong on 2018/10/31
"""
from flask import Blueprint

__author__ = 'dreamkong'

home = Blueprint('home', __name__)
from app.home import views

flask练习/movie_project/app/home/views.py
"""
Created by dreamkong on 2018/10/31
"""
import uuid
from datetime import datetime
from functools import wraps

import os
from werkzeug.utils import secure_filename

from app import bcrypt, db, rd
from app.home.forms import RegisterForm, LoginForm, UserDetailForm, PasswordForm, CommentForm
from app.models import User, UserLog, Preview, Tag, Movie, Comment, MovieFav

# from manage import app

__author__ = 'dreamkong'

from . import home
from flask import render_template, redirect, url_for, flash, request, session, current_app, Response


def change_filename(filename):
    fileinfo = os.path.splitext(filename)
    filename = datetime.now().strftime('%Y%m%d%H%M%S') + str(uuid.uuid4().hex) + fileinfo[-1]
    return filename


# 登录装饰器
def user_login_req(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not session.get('user'):
            return redirect(url_for('home.login', next=request.url))
        return f(*args, **kwargs)

    return decorated_function


@home.route('/<int:page>', methods=['GET'])
def index(page):
    tags = Tag.query.all()
    page_data = Movie.query
    # 标签
    tid = request.args.get('tid', 0)
    if int(tid) != 0:
        page_data = page_data.filter_by(tag_id=int(tid))
    # 星级
    star = request.args.get('star', 0)
    if int(star) != 0:
        page_data = page_data.filter_by(star=int(star))
    # 时间
    time = request.args.get('time', 0)
    if int(time) != 0:
        if int(time) == 1:
            page_data = page_data.order_by(Movie.add_time.desc())
        else:
            page_data = page_data.order_by(Movie.add_time.asc())
    # 播放量
    pm = request.args.get('pm', 0)
    if int(pm) != 0:
        if int(pm) == 1:
            page_data = page_data.order_by(
                Movie.play_nums.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.play_nums.asc()
            )
    # 评论量
    cm = request.args.get('cm', 0)
    if int(cm) != 0:
        if int(cm) == 1:
            page_data = page_data.order_by(
                Movie.comment_nums.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.comment_nums.asc()
            )
    if page is None:
        page = 1
    page_data = page_data.paginate(page=page, per_page=8)
    p = dict(
        tid=tid,
        star=star,
        time=time,
        pm=pm,
        cm=cm,
    )
    return render_template('home/index.html', tags=tags, p=p, page_data=page_data)


@home.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=data['name']).first()
        if user and not user.check_password(data['password']):
            flash('密码错误！', 'err')
            return redirect(url_for('home.login'))
        session['user'] = user.name
        session['user_id'] = user.id
        user_log = UserLog(
            user_id=user.id,
            ip=request.remote_addr
        )
        db.session.add(user_log)
        db.session.commit()
        return redirect(url_for('home.user'))
    return render_template('home/login.html', form=form)


@home.route('/logout/', methods=['GET'])
def logout():
    session.pop('user', None)
    session.pop('user_id', None)
    return redirect(url_for('home.login'))


@home.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        data = form.data
        user = User(
            name=data['name'],
            password=bcrypt.generate_password_hash(data['password']),
            email=data['email'],
            phone=data['phone'],
            uuid=uuid.uuid4().hex
        )
        db.session.add(user)
        db.session.commit()
        flash('注册成功！', 'ok')
    return render_template('home/register.html', form=form)


@home.route('/user/', methods=['GET', 'POST'])
@user_login_req
def user():
    form = UserDetailForm()
    user = User.query.get(int(session['user_id']))
    form.avatar.validators = []
    if request.method == 'GET':
        form.name.data = user.name
        form.email.data = user.email
        form.phone.data = user.phone
        form.info.data = user.info
    if form.validate_on_submit():
        data = form.data
        print(form.name)
        print(form.avatar)
        print(form.avatar.data)
        print(type(form.avatar.data))
        if form.avatar.data:
            file_avatar = secure_filename(form.avatar.data.filename)
            if not os.path.exists(current_app.config['UP_DIR']):
                os.makedirs(current_app.config['UP_DIR'])
            user.avatar = change_filename(file_avatar)
            form.avatar.data.save(current_app.config['UP_DIR'] + user.avatar)

        name_count = User.query.filter_by(name=data['name']).count()
        if data['name'] != user.name and name_count == 1:
            flash('昵称已经存在！', 'err')
            return redirect(url_for('home.user'))
        email_count = User.query.filter_by(email=data['email']).count()
        if data['email'] != user.email and email_count == 1:
            flash('邮箱已经存在！', 'err')
            return redirect(url_for('home.user'))
        phone_count = User.query.filter_by(phone=data['phone']).count()
        if data['phone'] != user.phone and phone_count == 1:
            flash('手机号码已经存在！', 'err')
            return redirect(url_for('home.user'))
        user.name = data['name']
        user.email = data['email']
        user.phone = data['phone']
        user.info = data['info']
        db.session.add(user)
        db.session.commit()
        flash('修改成功！', 'ok')
        return redirect(url_for('home.user'))
    return render_template('home/user.html', form=form, user=user)


@home.route('/pwd/', methods=['GET', 'POST'])
@user_login_req
def pwd():
    form = PasswordForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=session['user']).first()
        user.password = bcrypt.generate_password_hash(data['new_password'])
        db.session.add(user)
        db.session.commit()
        flash('修改密码成功，请重新登录！', 'ok')
        return redirect(url_for('home.logout'))
    return render_template('home/pwd.html', form=form)


@home.route('/comments/<int:page>', methods=['GET', 'POST'])
@user_login_req
def comments(page):
    if page is None:
        page = 1
    page_data = Comment.query.join(Movie).filter(Comment.movie_id == Movie.id,
                                                 Comment.user_id == session['user_id']).order_by(
        Comment.add_time.desc()).paginate(per_page=current_app.config['PER_PAGE'], page=page)
    return render_template('home/comments.html', page_data=page_data)


@home.route('/loginlog/<int:page>', methods=['GET', 'POST'])
@user_login_req
def loginlog(page):
    if page is None:
        page = 1
    page_data = UserLog.query.filter_by(user_id=int(session['user_id'])).order_by(
        UserLog.add_time.desc()).paginate(per_page=current_app.config['PER_PAGE'],
                                          page=page)
    return render_template('home/loginlog.html', page_data=page_data)


@home.route('/moviefav/<int:page>', methods=['GET', 'POST'])
@user_login_req
def moviefav(page):
    if page is None:
        page = 1
    page_data = MovieFav.query.join(Movie).filter(MovieFav.movie_id == Movie.id,
                                                  MovieFav.user_id == session['user_id']).order_by(
        MovieFav.add_time.desc()).paginate(per_page=current_app.config['PER_PAGE'], page=page)
    return render_template('home/moviefav.html', page_data=page_data)


@home.route('/moviefav/add', methods=['GET'])
@user_login_req
def moviefav_add():
    mid = request.args.get('mid', '')
    uid = request.args.get('uid', '')
    moviefav_count = MovieFav.query.filter(MovieFav.movie_id == int(mid), MovieFav.user_id == int(uid)).count()
    if moviefav_count == 1:
        data = dict(ok=0)
    else:
        moviefav = MovieFav(
            movie_id=mid,
            user_id=uid
        )
        db.session.add(moviefav)
        db.session.commit()
        data = dict(ok=1)
    import json
    return json.dumps(data)


@home.route('/animation/', methods=['GET', 'POST'])
def animation():
    data = Preview.query.all()
    return render_template('home/animation.html', data=data)


@home.route('/search/<int:page>', methods=['GET', 'POST'])
def search(page):
    if page is None:
        page = 1
    key = request.args.get('key', "")
    movie_count = Movie.query.filter(Movie.title.ilike('%' + key + '%')).order_by(
        Movie.add_time.desc()).count()
    page_data = Movie.query.filter(Movie.title.ilike('%' + key + '%')).order_by(Movie.add_time.desc()).paginate(
        per_page=10, page=page)
    return render_template('home/search.html', page_data=page_data, movie_count=movie_count, key=key)


@home.route('/play/<int:id>/<int:page>', methods=['GET', 'POST'])
def play(id, page):
    movie = Movie.query.join(Tag).filter(Movie.tag_id == Tag.id, Movie.id == int(id)).first_or_404()
    if page is None:
        page = 1
    page_data = Comment.query.join(Movie).join(User).filter(Comment.movie_id == Movie.id,
                                                            Comment.user_id == User.id).order_by(
        Comment.add_time.desc()).paginate(per_page=current_app.config['PER_PAGE'], page=page)
    movie.play_nums = movie.play_nums + 1
    db.session.add(movie)
    db.session.commit()
    form = CommentForm()
    if form.validate_on_submit():
        data = form.data
        comment = Comment(
            content=data['content'],
            user_id=session['user_id'],
            movie_id=movie.id
        )
        db.session.add(comment)
        movie.comment_nums = movie.comment_nums + 1
        db.session.add(movie)
        db.session.commit()
        flash('添加评论成功！', 'ok')
        return redirect(url_for('home.play', id=movie.id, page=1))

flask练习/movie_project/app/templates/home/animation.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>热映电影</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='anim/css/style.css') }}">
</head>
<body>
<!--轮播图 开始 -->
<div class="main_banner">
    <div class="main_banner_wrap">
        <canvas id="myCanvas" width="150" height="150"></canvas>
        <div class="main_banner_box" id="m_box">
            <a href="javascript:void(0)" class="banner_btn js_pre">
                <span class="banner_btn_arrow"><i></i></span>
            </a>
            <a href="javascript:void(0)" class="banner_btn btn_next js_next">
                <span class="banner_btn_arrow"><i></i></span>
            </a>
            <ul>
                {% for i in data %}
                    <li id="imgCard{{ i.id-1 }}">
                        <a href=""><span style="opacity:0;"></span></a>
                        <img src="{{ url_for('static', filename='uploads/'+i.logo) }}" alt="">
                        <p style="bottom:0">{{ i.title }}</p>
                    </li>
                {% endfor %}
            </ul>
            <!--火狐倒影图层-->
            <p id="rflt"></p>
            <!--火狐倒影图层-->
        </div>
        <!--序列号按钮-->
        <div class="btn_list">
            <span class="curr"></span><span></span><span></span><span></span><span></span>
        </div>
    </div>

</div>
<!--轮播图 结束 -->

<script type="text/javascript" src="{{ url_for('static', filename='anim/js/jquery.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='anim/js/script.js') }}"></script>

</body>
</html>

flask练习/movie_project/app/templates/home/comments.html
{% extends 'home/home.html' %}
{% import 'ui/home_page.html' as pg %}
{% block content %}
    {% include 'home/menu.html' %}
    <div class="col-md-9">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;评论记录</h3>
            </div>
            <div class="panel-body">
                <ul class="commentList">
                    {% for i in page_data.items %}
                        <li class="item cl">
                            <a href="{{ url_for('home.user') }}">
                                <i class="avatar size-L radius">
                                    {% if i.user.avatar %}
                                                <img alt="50x50"
                                                     src="{{ url_for('static',filename='uploads/'+i.user.avatar) }}"
                                                     class="img-circle"
                                                     style="border:1px solid #abcdef;width: 50px;height: 50px">
                                            {% else %}
                                                <img alt="50x50"
                                                     data-src="holder.js/50x50"
                                                     class="img-circle"
                                                     style="border:1px solid #abcdef;width: 50px;height: 50px">
                                            {% endif %}
                                </i>
                            </a>
                            <div class="comment-main">
                                <header class="comment-header">
                                    <div class="comment-meta">
                                        评论&nbsp;<a class="comment-author"
                                             href="{{ url_for('home.play',id=i.movie.id,page=1) }}">{{ i.movie.title }}</a>&nbsp;于
                                        <time title="{{ i.add_time }}" datetime="{{ i.add_time }}">
                                            {{ i.add_time }}
                                        </time>
                                    </div>
                                </header>
                                <div class="comment-body">
                                    <p>{{ i.content | safe }}</p>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                <div class="col-md-12 text-center">
                    {{ pg.page(page_data,'home.comments') }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        $(document).ready(function () {
            $('#m-3').addClass('active')
        });
    </script>
{% endblock %}

flask练习/movie_project/app/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/animate.css') }}">
    <style>
        .navbar-brand > img {
            display: inline;
        }

        .media {
            padding: 3px;
            border: 1px solid #ccc
        }
    </style>
    {% block css %}{% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index',page=1) }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static', filename='base/images/logo.png') }}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！" id="key_movie">
                    <span class="input-group-btn" id="do_search">
                        <a class="btn btn-default">
                            <span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index',page=1) }}"><span
                            class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.login') }}"><span
                            class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.register') }}"><span
                            class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.logout') }}"><span
                            class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
    {% block content %}{% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2017&nbsp;flaskmovie.imooc.com&nbsp;京ICP备 13046642号-2
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static', filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static', filename='lazyload/jquery.lazyload.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function () {
        new WOW().init();
    });

    $(document).ready(function () {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
        $("#do_search").click(function () {
            var key = $("#key_movie").val();
            location.href = "{{ url_for('home.search',page=1) }}?key=" + key
        })
    });
</script>
{% block js %}{% endblock %}
</body>
</html>

flask练习/movie_project/app/templates/home/layout.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/animate.css') }}">
    <style>
        .navbar-brand > img {
            display: inline;
        }

        .media {
            padding: 3px;
            border: 1px solid #ccc
        }
    </style>
    {% block css %}{% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="index.html" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static', filename='base/images/logo.png') }}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！">
                    <span class="input-group-btn">
                        <a class="btn btn-default" href="{{ url_for('home.search',page=1) }}"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index',page=1) }}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.login') }}"><span
                            class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.register') }}"><span
                            class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.logout') }}"><span
                            class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->

    {% block content %}{% endblock %}

<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2017&nbsp;flaskmovie.imooc.com&nbsp;京ICP备 13046642号-2
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static', filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static', filename='lazyload/jquery.lazyload.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function () {
        new WOW().init();
    });

    $(document).ready(function () {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
    });
</script>
{% block js %}{% endblock %}
</body>
</html>

flask练习/movie_project/app/templates/home/menu.html
<div class="col-md-3">
    <div class="list-group">
        <a id="m-1" href="{{ url_for('home.user') }}" class="list-group-item">
            <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
        </a>
        <a id="m-2" href="{{ url_for('home.pwd') }}" class="list-group-item">
            <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
        </a>
        <a id="m-3" href="{{ url_for('home.comments',page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
        </a>
        <a id="m-4" href="{{ url_for('home.loginlog',page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
        </a>
        <a id="m-5" href="{{ url_for('home.moviefav',page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
        </a>
    </div>
</div>